// glosario.js — Diccionario en lenguaje simple.
// Se usa en la app Y en el manual: cualquier palabra de estas aparece
// subrayada y, al tocarla, muestra su explicación. (Ver gloss.js)
// Cada entrada: keys = formas en que puede aparecer el texto · t = título · d = explicación llana.

// OJO: se asigna a window.GLOSARIO (NO `const`). Un `const` a nivel de script
// NO queda en window, y gloss.js lo lee como window.GLOSARIO → si fuera const,
// gloss.js recibiría lista vacía y armaría un regex que cuelga la página.
window.GLOSARIO = [
  { keys:['nitrógeno','nitrogeno'], t:'Nitrógeno (N)',
    d:'Es el "alimento del crecimiento verde": hace que la planta saque hojas y ramas. Si le pones de más, tendrás mucha hoja y pocos frutos.' },
  { keys:['fósforo','fosforo'], t:'Fósforo (P)',
    d:'Ayuda a la planta a formar raíces fuertes y a arrancar bien. Por eso se pone todo al principio, al sembrar.' },
  { keys:['potasio'], t:'Potasio (K)',
    d:'Ayuda a que el fruto se llene, tenga buen sabor y aguante guardado sin dañarse. Se refuerza en la etapa final.' },
  { keys:['15-30-8','fórmula 15-30-8','formula 15-30-8'], t:'Fórmula 15-30-8',
    d:'Un abono completo. Los tres números son el % de Nitrógeno–Fósforo–Potasio que trae (15% N, 30% P, 8% K). Como tiene mucho fósforo, es ideal para el arranque.' },
  { keys:['urea'], t:'Urea',
    d:'Un abono que aporta sobre todo nitrógeno (crecimiento de hojas y ramas). Se esparce alrededor de la planta con la tierra húmeda.' },
  { keys:['sulfato de potasio'], t:'Sulfato de potasio',
    d:'Un abono que aporta potasio, para que el fruto llene bien y se conserve más tiempo.' },
  { keys:['curado','curar'], t:'Curado',
    d:'Dejar los zapallos ya cosechados al calor y aire seco unos 8 a 10 días antes de guardarlos. Esto endurece la cáscara y cierra las heridas, para que duren meses sin pudrirse.' },
  { keys:['cuaje','cuajar','cuajen'], t:'Cuaje',
    d:'Es cuando la flor, ya polinizada, empieza a convertirse en fruto. "Buen cuaje" quiere decir que muchas flores llegan a ser zapallos.' },
  { keys:['guía','guías','guia','guias'], t:'Guía',
    d:'Cada rama larga y rastrera del zapallo, la que se va extendiendo por el suelo.' },
  { keys:['raleo','ralear'], t:'Raleo',
    d:'Quitar plantas (o frutos) de más para dejar solo los mejores, de modo que no compitan por agua y comida y crezcan más sanos.' },
  { keys:['vegetativa','fase vegetativa'], t:'Fase vegetativa',
    d:'La primera etapa del cultivo: la planta solo hace hojas, raíces y ramas, todavía sin flores. Dura alrededor de 40 días.' },
  { keys:['reproductiva','fase reproductiva'], t:'Fase reproductiva',
    d:'La etapa de las flores y de la formación de frutos. Aquí las abejas y un riego parejo son claves.' },
  { keys:['maduración','maduracion'], t:'Maduración',
    d:'La etapa final: el fruto termina de crecer y cambia de color. Se riega menos para mejorar la calidad y que aguante guardado.' },
  { keys:['polinización','polinizacion','polinizadores','polinizar'], t:'Polinización',
    d:'Es llevar el polen de la flor macho a la flor hembra. Sin esto no hay fruto. Lo hacen sobre todo las abejas, por la mañana.' },
  { keys:['umbral'], t:'Umbral de control',
    d:'La cantidad de plaga a partir de la cual conviene actuar. Con menos, no vale la pena fumigar; con más, sí.' },
  { keys:['bacillus thuringiensis','bt'], t:'Bt (Bacillus thuringiensis)',
    d:'Un control biológico: una bacteria natural que mata orugas y gusanos, pero no daña a las abejas ni a las personas.' },
  { keys:['añublo lanoso','anublo lanoso','mildiu'], t:'Añublo lanoso (mildiu)',
    d:'Un hongo que aparece con humedad: manchas amarillas arriba de la hoja y una pelusa gris por debajo. Se previene con buen aireado y riego por goteo (sin mojar la hoja).' },
  { keys:['añublo polvoriento','anublo polvoriento','oídio','oidio'], t:'Añublo polvoriento (oídio)',
    d:'Un hongo que se ve como un polvo blanco sobre las hojas. Se controla temprano; hay variedades que le resisten.' },
  { keys:['damping-off','mal del almácigo','mal del almacigo'], t:'Mal del almácigo (damping-off)',
    d:'Hongos que "ahogan" a la plantita recién nacida a la altura del tallo, sobre todo cuando la tierra está muy húmeda.' },
  { keys:['etileno'], t:'Etileno',
    d:'Un gas invisible que sueltan frutas como la manzana y el banano, y que hace madurar (y pudrir) más rápido lo que esté cerca. Por eso los zapallos se guardan lejos de ellas.' },
  { keys:['monoica'], t:'Planta monoica',
    d:'Que tiene flores macho y flores hembra separadas, pero en la misma planta. Solo las hembra dan fruto, si son polinizadas.' },
  { keys:['pedúnculo','pedunculo','rabito'], t:'Pedúnculo (el "rabito")',
    d:'El pedacito de tallo que une el fruto con la planta. Al cosechar hay que dejárselo (3 a 5 cm): sin él, el zapallo se pudre por ahí.' },
  { keys:['acolchado','mulching'], t:'Acolchado (mulching)',
    d:'Cubrir el suelo alrededor de las plantas (con plástico o paja). Controla malezas, ahorra agua y adelanta la cosecha.' },
  { keys:['fertirriego','fertirriega','fertirrigación','fertirrigacion'], t:'Fertirriego',
    d:'Echar el abono disuelto en el agua de riego por goteo, en dosis pequeñas y frecuentes. Se aprovecha mucho mejor el fertilizante.' },
  { keys:['injerto','injertar'], t:'Injerto',
    d:'Pegar la planta de zapallo sobre la raíz de otra planta resistente, para que tolere enfermedades del suelo y crezca con más fuerza.' },
  { keys:['mip','manejo integrado de plagas'], t:'MIP (Manejo Integrado de Plagas)',
    d:'Controlar las plagas combinando prevención, revisión frecuente y umbrales, en vez de fumigar por calendario. Se usa veneno solo cuando de verdad hace falta.' },
  { keys:['ppm'], t:'ppm (partes por millón)',
    d:'Una medida de cuánto nutriente hay en el suelo. La da el análisis de suelo del laboratorio y sirve para saber cuánto abono falta.' },
  { keys:['dds'], t:'dds (días después de la siembra)',
    d:'Forma corta de contar el tiempo del cultivo desde el día que sembraste. "45 dds" = 45 días después de sembrar.' },
  { keys:['quintal','qq'], t:'Quintal (qq)',
    d:'Una medida de peso usada en el campo. En esta guía, 1 quintal equivale a unos 46 kilos.' },
  { keys:['ingrediente activo','i.a.'], t:'Ingrediente activo (i.a.)',
    d:'La parte del producto (herbicida o fungicida) que de verdad hace el efecto. Las dosis en "g i.a./ha" se refieren a esa parte pura por hectárea.' },
  { keys:['p₂o₅','p2o5'], t:'P₂O₅',
    d:'La forma técnica de medir el fósforo del abono en los análisis. Es solo otra manera de nombrar el fósforo (P).' },
  { keys:['k₂o','k2o'], t:'K₂O',
    d:'La forma técnica de medir el potasio del abono. Es solo otra manera de nombrar el potasio (K).' },
  { keys:['n 30/40/30','30/40/30'], t:'Nitrógeno 30/40/30',
    d:'Cómo repartir el nitrógeno en 3 momentos: 30% al sembrar, 40% cuando aparecen las flores, y 30% al llenarse los frutos. Así la planta recibe alimento justo cuando lo necesita, sin desperdicio.' },
  { keys:['k 70/30','70/30'], t:'Potasio 70/30',
    d:'Cómo repartir el potasio: 70% durante el crecimiento y 30% en la maduración (cuando el fruto se está llenando).' },
  { keys:['zapallo de guarda','de guarda'], t:'Zapallo de guarda',
    d:'El zapallo de cáscara dura, pensado para guardarse muchos meses. Es distinto del zapallito tierno (tipo calabacín), que se come enseguida.' },
  { keys:['cucurbitácea','cucurbitáceas','cucurbitacea','cucurbitaceas'], t:'Cucurbitáceas',
    d:'La familia de plantas del zapallo: incluye pepino, melón, sandía y calabaza. Comparten plagas y enfermedades, por eso no conviene sembrarlas una tras otra en el mismo lugar.' },
  { keys:['híbrido','hibrido','híbrido f1','f1'], t:'Híbrido F1',
    d:'Una semilla del cruce de dos líneas seleccionadas. Rinde más, es más pareja y suele resistir mejor las enfermedades. Ojo: NO conviene guardar su semilla, porque la siguiente generación sale despareja; se compra cada vez.' },
  { keys:['moschata','cucurbita moschata'], t:'Cucurbita moschata',
    d:'Una de las especies de zapallo (la del ayote, butternut y el Arjuna). Aguanta mejor el calor, la humedad y varias plagas/virus del trópico que el zapallo criollo (Cucurbita maxima).' },
  { keys:['msnm'], t:'msnm (metros sobre el nivel del mar)',
    d:'La altura del terreno respecto al mar. Sirve para saber si una variedad se da bien en tu zona: "0 a 1.800 msnm" = desde la costa hasta media montaña.' },
  { keys:['t/ha','toneladas por hectárea'], t:'t/ha (toneladas por hectárea)',
    d:'Cuántas toneladas se cosechan en una hectárea (10.000 m², como un cuadrado de 100×100 m). Es la medida del rendimiento: más t/ha = más kilos por el mismo terreno.' },
  { keys:['fruto por planta','frutos por planta','carga'], t:'Frutos por planta (carga)',
    d:'Cuántos zapallos aguanta y llena cada planta. Para máximo rendimiento total conviene que cuajen y llenen varios; para un fruto gigante, se deja uno solo.' },
];
